os:
    - linux
language: node_js
node_js:
    - '8'
    - '9'
    - '10'
    - '11'
    - '12'
addons:
    sauce_connect:
        username: compodoc
    jwt:
        secure: Pij3Z+chkGBAHK5S2fTEEmsKlt+5wDkKB2bbKUQ3QWW+WSFg+tTh3KlK6I5qhFC8TC1zqZpaZMZZTEIcIz/hNXdIKQjFUv+91WRqQZRfNJvbnaPV5ZDcK/SN8hSR+Q//dTWlCWTMGGGWGVJwX8AzE0JEphrwSbXq7T1/zdrNFffQ1qqPioqMVRJ/2PAqzNAHMuOo6YfWBze4F2bvHR87bcM9DBhAJSvFjVf1qv0+3aJxo9UPjpBPVo4YgNzwFQzhHyGAvYBOfSBu8g5MMG9Sc4oGjVformPEmglCLCJCxT92wZvU0sopoAedfcTgWgTrdDTNDS/Rx91Xv0vuMg0F1CA/5BRqvcTBGKUB4QLIIWvqLV3NGlJbe0DE0E+Netje8ci+0DSE6EqTeN/v/Up02VKNrjL7Eyz8g2sv6vM8c0roY54+o5xxtyuJQTs5KndXsAHylCGj+SkU+hRYbCxfs++hPMqXUbjDUA6/ezhGvSHIdeTWOMs4BEz6BMgIlZLP+3Z4o2FT3+cWGbEOc0nrawATlbNcexpHNBBW5ihvcpdmFqYdUYtzLPVGPvaIlMhFY+guBqIgKjXxAI0AjV6UruKKeQnfHhONuRw5pQFEb4lDJpVE99gnPLaKs7mpIgEVPbAegZF9T2TsZ7xxYwFjaM17NrS2KkQlk6IgkhxgemE=
    sonarcloud:
        organization: 'compodoc'
        token:
            secure: ZwCJRNo0yhGRNYKAwUmfWFibIzzk7xHK9GZIx/0D6j6Ln3h0RAzuTgbXcrDCxxCwG8xdORrkVn6jpmkh5FcFR30xgShVtCbass/epgUJCxEDpE+vlP2oXUOxcRW3IKqcRx+zm4CfO8ggDFGShiiCx8qDbdFf/U+vqW/V8I4hrsK9PwiNhl8Xil2OatDgpgdkeKCDEW90U5h2iBm6SOWfR9HxDv7OAujqRBewsri6i356ea7Y2aeiZkzcye1gArZfMFH5GqbPDoJ3/OpUJj3y+q2jXFn2H/s4MhzPpNLg93NnDc6KRNw3vvs9w8BbI6TCVWbm/uwpnB+vOHRpKr/VVHURAwdunCku5kJpBcobkf8hUnTitKXNxEpq4VPvsbzCkPSGdWJ0ci20vB9CFsvwJfjm8wBBmWiT5QdX42Q4XDfsT647X9v7ivYxpOcKDG3+uLkCQYLxeI7w8eSR2y2UZrrGokiLk5yFacifk2klmnQvQrNuk1cfV/QipKFqkFyeAK+BWr8MJdY5Tk39iQYiKYohAyx4JtKJ/zpmxNSD+dDDegZa2e/byq+3oF/ymd9iSOOLFfmvZbctSOVDXN1r95QqcUWR3rVYrTQRwAYQpA/YlfCfWOmXMMjzsN1Dweg1OKbp8pSoJyxVHiNJxzXs7Fpex+z4SQS47fXSKMStPH4=
install:
    - npm install npm@latest -g
    - npm ci
script:
    - npm run build
    - npm run test
    - if [ $TO_TEST == 'UNIT' ]; then sonar-scanner; fi
    - if [ $TO_TEST == 'ALL' ]; then npm run saucelabs-test-e2e-mocha; fi
    - if [ $TO_TEST == 'OTHERS' ]; then npm run angularexpo; fi
after_success:
    - npm run codecov
branches:
    only:
        - develop
matrix:
    allow_failures:
        - os: osx
        - node_js: '11'
        - node_js: '12'
    exclude:
        - node_js: '8'
        - node_js: '9'
        - node_js: '10'
        - node_js: '11'
        - node_js: '12'
    include:
        - node_js: '8'
          env: TO_TEST=UNIT SAUCE_USERNAME=compodoc
        - node_js: '9'
          env: TO_TEST=OTHERS SAUCE_USERNAME=compodoc
        - node_js: '10'
          env: TO_TEST=ALL SAUCE_USERNAME=compodoc
        - node_js: '11'
          env: TO_TEST=UNIT SAUCE_USERNAME=compodoc
        - node_js: '12'
          env: TO_TEST=UNIT SAUCE_USERNAME=compodoc
